### ISSUE TITLE
baby8 bom

### ISSUE THREAD

**Issue by reaganryl** [mzuelch/CATs-Eurosynth#2]
hi! i got some pcbs made up with your baby8 gerbers. is there a bom? now I see it says 'reworking'- is there an ez fix with these boards? thanks!

**Comment by mzuelch** [comment]
Sorry for the late reply - I had some private issues during the last weeks.

The BOM is now included as an iBOM. The reason for the "rework" mark is the trigger input stage (CLK and RESET). Sadly it's quite picky when it comes to recognizing the signal.

**Comment by reaganryl** [comment]
Thanks! Hope all is well.

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by reaganryl** [comment]
I just put a 100nf cap between the clock jack pin and the board and it's working great now.

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------
